name: morning_routine_app
description: "Morning routine tracker for children"
publish_to: 'none'
version: 1.0.2+3

environment:
  sdk: ^3.11.3

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  flutter_riverpod: ^2.6.1
  hive_flutter: ^1.1.0
  hive: ^2.2.3
  shared_preferences: ^2.3.3
  go_router: ^14.8.1
  flutter_svg: ^2.0.10+1
  uuid: ^4.5.1
  intl: ^0.20.2
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.13

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/avatars/
